### ISSUE TITLE
Contact list response is not working

### ISSUE THREAD

**Issue by Shofol** [plentymarkets/plugin-terra-basic#34]
Hello, I've cloned the repo and just changed the domain name and authToken. When I am requesting by pressing the search button the request shows success but no result is coming. In postman, it is returning an HTML page. Can anyone help? 

[Request from browser] (https://imgbbb.com/images/2019/11/06/Captured4a70f22dc8906ec.png)
[Request from postman] (https://imgbbb.com/images/2019/11/06/Captures.png)

**Comment by JVolke** [comment]
Hi @Shofol,

you have to use your public url before "/rest/accounts/contact" and not the backend url. It should look like this: "https://yourdomain.de/rest/accounts/contact/"

**Comment by Shofol** [comment]
Thanks for the reply @JVolke but it is a bit too late for me :/ The client has gone! I hope it may help someone in the future.
